title: Christian Lentz
email: clentz[at]macalester.edu
description: Macalester College, Mathematics and Compter Science
url: https://christianlentz.github.io/

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed